# Generated by Django 4.2.5 on 2023-09-11 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentgrade",
            options={"verbose_name": "Grade"},
        ),
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name_plural": "Comments"},
        ),
        migrations.RemoveField(
            model_name="post",
            name="dislikes_count",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes_count",
        ),
    ]
