# Generated by Django 4.2.5 on 2023-09-11 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_commentgrade_options_alter_comments_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommentGrade",
        ),
    ]
